data:
  raw: data/raw/winequality-red.csv
  intermediate: data/intermediate
model: model/svm.pkl
process:
  feature: quality
  test_size: 0.2
train:
  hyperparameters:
    svm__kernel:
    - linear
    - rbf
    svm__C:
    - 0.1
    - 1
    - 10
    - 100
    svm__gamma:
    - 0.1
    - 1
    - 10
  grid_search:
    cv: 5
    scoring: accuracy
    verbose: 3
